import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'tl';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Login
    'login.title': 'Welcome Back',
    'login.subtitle': 'Sign in to continue',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.showPassword': 'Show Password',
    'login.signin': 'Sign In',
    'login.signingIn': 'Signing In...',
    'login.noAccount': "Don't have an account?",
    'login.signUp': 'Sign Up',
    'login.capsLock': 'Caps Lock is ON',
    
    // Register
    'register.title': 'Create Account',
    'register.subtitle': 'Join KapeRest today',
    'register.firstName': 'First Name',
    'register.middleName': 'Middle Name',
    'register.lastName': 'Last Name',
    'register.email': 'Email Address',
    'register.password': 'Password',
    'register.role': 'Select Role',
    'register.branch': 'Select Branch',
    'register.assignCashier': 'Assign to Cashier',
    'register.showPassword': 'Show Password',
    'register.createAccount': 'Create Account',
    'register.creating': 'Creating...',
    'register.haveAccount': 'Already have an account?',
    'register.signIn': 'Sign In',
    
    // Common
    'common.brandName': 'KapeRest',
    'common.posSystem': 'Point of Sale System',
    'common.language': 'Language',
    'common.logout': 'Logout',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.print': 'Print',
    'common.refresh': 'Refresh',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.loading': 'Loading...',
    'common.noData': 'No data available',
    'common.success': 'Success',
    'common.error': 'Error',
    
    // Admin Dashboard
    'admin.dashboard': 'Admin Dashboard',
    'admin.systemOverview': 'System Overview',
    'admin.totalUsers': 'Total Users',
    'admin.activeBranches': 'Active Branches',
    'admin.totalRevenue': 'Total Revenue',
    'admin.allTimeSales': 'All-time sales',
    'admin.operatingLocations': 'Operating locations',
    'admin.salesTrendAnalysis': 'Sales Trend Analysis',
    'admin.accounts': 'Accounts',
    'admin.branches': 'Branches',
    'admin.inventory': 'Inventory',
    'admin.sales': 'Sales',
    'admin.auditTrail': 'Audit Trail',
    'admin.goodMorning': 'Good Morning',
    'admin.goodAfternoon': 'Good Afternoon',
    'admin.goodEvening': 'Good Evening',
    'admin.today': 'Today',
    'admin.fullSystemControl': 'Full System Control',
    'admin.oneDay': '1 Day',
    'admin.sevenDays': '7 Days',
    'admin.thirtyDays': '30 Days',
    'admin.custom': 'Custom',
    'admin.selectDateRange': 'Select Date Range',
    'admin.fromDate': 'From Date',
    'admin.toDate': 'To Date',
    'admin.applyRange': 'Apply Range',
    'admin.cancel': 'Cancel',
    'admin.loadingSalesData': 'Loading sales data...',
    'admin.error': 'Error',
    'admin.orders': 'orders',
    'admin.revenueTrend': 'Revenue Trend',
    'admin.salesPerformance': 'Sales performance',
    'admin.revenue': 'Revenue',
    'admin.transactions': 'Transactions',
    'admin.min': 'Min',
    'admin.avg': 'Avg',
    'admin.max': 'Max',
    'admin.last7Days': 'Last 7 days',
    'admin.last24Hours': 'Last 24 hours',
    'admin.last30Days': 'Last 30 days',
    'admin.customPeriod': 'Custom period',
    'admin.noSalesData': 'No sales data available for the selected period.',
    'admin.quickTips': 'Quick Tips',
    'admin.tipsDescription': 'Use the sidebar to manage the system. Access',
    'admin.userManagement': '👥 User Management',
    'admin.branchControl': '🏢 Branch Control',
    'admin.analytics': '📊 Analytics',
    'admin.trackPerformance': 'Track performance over time',
    
    // Staff Dashboard
    'staff.dashboard': 'Staff Dashboard',
    'staff.items': 'Items',
    'staff.suppliers': 'Suppliers',
    'staff.stocks': 'Stocks',
    'staff.addItem': 'Add Item',
    'staff.addSupplier': 'Add Supplier',
    'staff.addStocks': 'Add Stocks',
    'staff.voidRequests': 'Void Requests',
    'staff.purchases': 'Purchases',
    'staff.changePassword': 'Change Password',
    
    // Cashier Dashboard
    'cashier.dashboard': 'Cashier Dashboard',
    'cashier.buyItem': 'Buy Item',
    'cashier.sales': 'Sales',
    'cashier.holdItems': 'Hold Items',
    'cashier.purchases': 'Purchases',
    'cashier.mainPanel': 'Main Panel',
    
    // Sidebar
    'sidebar.home': 'Home',
    'sidebar.dashboard': 'Dashboard',
    'sidebar.inventory': 'Inventory',
    'sidebar.sales': 'Sales',
    'sidebar.reports': 'Reports',
    'sidebar.settings': 'Settings',
    
    // Purchases Page
    'purchases.title': 'Purchases',
    'purchases.subtitle': 'Transaction history',
    'purchases.searchPlaceholder': 'Search purchases...',
    'purchases.found': 'found',
    'purchases.voidRequests': 'Void Requests',
    'purchases.allPayments': 'All Payments',
    'purchases.cash': 'Cash',
    'purchases.gcash': 'GCash',
    'purchases.allStatus': 'All Status',
    'purchases.completed': 'Completed',
    'purchases.voided': 'Voided',
    'purchases.purchaseHistory': 'Purchase History',
    'purchases.allTransactionRecords': 'All transaction records',
    'purchases.loading': 'Loading purchases...',
    'purchases.noPurchases': 'No purchases found',
    'purchases.tryAdjusting': 'Try adjusting your search',
    'purchases.saleId': 'Sale ID',
    'purchases.receiptNo': 'Receipt No.',
    'purchases.itemName': 'Item Name',
    'purchases.dateTime': 'Date & Time',
    'purchases.subtotal': 'Subtotal',
    'purchases.tax': 'Tax',
    'purchases.discount': 'Discount',
    'purchases.total': 'Total',
    'purchases.payment': 'Payment',
    'purchases.status': 'Status',
    'purchases.actions': 'Actions',
    'purchases.void': 'Void',
    'purchases.alreadyVoided': 'Already voided',
    'purchases.voidThisPurchase': 'Void this purchase',
    'purchases.confirmVoid': 'Are you sure you want to void this purchase? This action will restore the stock.',
    'purchases.authError': 'Authorization error. Please log in again.',
    'purchases.voidFailed': 'Failed to void purchase.',
    'purchases.tryAgain': 'Please try again.',
    
    // Void Requests Page
    'voidRequests.title': 'Void Requests',
    'voidRequests.subtitle': 'Review and approve/reject void requests from cashiers',
    'voidRequests.searchPlaceholder': 'Search by receipt number, item name...',
    'voidRequests.loading': 'Loading void requests...',
    'voidRequests.noRequests': 'No pending void requests',
    'voidRequests.allClear': 'All clear! No void requests at the moment.',
    'voidRequests.receiptNo': 'Receipt No.',
    'voidRequests.itemName': 'Item Name',
    'voidRequests.dateTime': 'Date & Time',
    'voidRequests.total': 'Total',
    'voidRequests.payment': 'Payment',
    'voidRequests.approve': 'Approve',
    'voidRequests.reject': 'Reject',
    'voidRequests.confirmApprove': 'Are you sure you want to approve this void request? This will restore the stock and void the transaction.',
    'voidRequests.confirmReject': 'Are you sure you want to reject this void request?',
    'voidRequests.approveSuccess': 'Void request approved successfully',
    'voidRequests.rejectSuccess': 'Void request rejected',
    'voidRequests.approveFailed': 'Failed to approve void request',
    'voidRequests.rejectFailed': 'Failed to reject void request',
  },
  tl: {
    // Login (Tagalog)
    'login.title': 'Maligayang Pagbabalik',
    'login.subtitle': 'Mag-sign in para magpatuloy',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.showPassword': 'Ipakita ang Password',
    'login.signin': 'Mag-sign In',
    'login.signingIn': 'Nag-sign In...',
    'login.noAccount': 'Walang account?',
    'login.signUp': 'Mag-sign Up',
    'login.capsLock': 'Caps Lock ay NAKABUKAS',
    
    // Register (Tagalog)
    'register.title': 'Gumawa ng Account',
    'register.subtitle': 'Sumali sa KapeRest ngayon',
    'register.firstName': 'Pangalan',
    'register.middleName': 'Gitnang Pangalan',
    'register.lastName': 'Apelyido',
    'register.email': 'Email Address',
    'register.password': 'Password',
    'register.role': 'Pumili ng Role',
    'register.branch': 'Pumili ng Branch',
    'register.assignCashier': 'I-assign sa Cashier',
    'register.showPassword': 'Ipakita ang Password',
    'register.createAccount': 'Gumawa ng Account',
    'register.creating': 'Gumagawa...',
    'register.haveAccount': 'May account na?',
    'register.signIn': 'Mag-sign In',
    
    // Common
    'common.brandName': 'KapeRest',
    'common.posSystem': 'Point of Sale System',
    'common.language': 'Wika',
    'common.logout': 'Mag-logout',
    'common.save': 'I-save',
    'common.cancel': 'Kanselahin',
    'common.delete': 'Burahin',
    'common.edit': 'I-edit',
    'common.add': 'Magdagdag',
    'common.search': 'Maghanap',
    'common.filter': 'I-filter',
    'common.export': 'I-export',
    'common.print': 'I-print',
    'common.refresh': 'I-refresh',
    'common.close': 'Isara',
    'common.confirm': 'Kumpirmahin',
    'common.loading': 'Naglo-load...',
    'common.noData': 'Walang available na data',
    'common.success': 'Tagumpay',
    'common.error': 'May Error',
    
    // Admin Dashboard
    'admin.dashboard': 'Admin Dashboard',
    'admin.systemOverview': 'Sistema Overview',
    'admin.totalUsers': 'Users',
    'admin.activeBranches': 'Branches',
    'admin.totalRevenue': 'Kita',
    'admin.allTimeSales': 'Total benta',
    'admin.operatingLocations': 'Lokasyon',
    'admin.salesTrendAnalysis': 'Sales Analysis',
    'admin.accounts': 'Mga Account',
    'admin.branches': 'Mga Branch',
    'admin.inventory': 'Imbentaryo',
    'admin.sales': 'Benta',
    'admin.auditTrail': 'Audit Trail',
    'admin.goodMorning': 'Magandang Umaga',
    'admin.goodAfternoon': 'Magandang Hapon',
    'admin.goodEvening': 'Magandang Gabi',
    'admin.today': 'Ngayon',
    'admin.fullSystemControl': 'Sistema Control',
    'admin.oneDay': '1 Araw',
    'admin.sevenDays': '7 Araw',
    'admin.thirtyDays': '30 Araw',
    'admin.custom': 'Custom',
    'admin.selectDateRange': 'Piliin ang Petsa',
    'admin.fromDate': 'Mula',
    'admin.toDate': 'Hanggang',
    'admin.applyRange': 'I-apply',
    'admin.cancel': 'Kanselahin',
    'admin.loadingSalesData': 'Naglo-load ng sales...',
    'admin.error': 'May Error',
    'admin.orders': 'orders',
    'admin.revenueTrend': 'Revenue Trend',
    'admin.salesPerformance': 'Sales performance',
    'admin.revenue': 'Kita',
    'admin.transactions': 'Transaksyon',
    'admin.min': 'Min',
    'admin.avg': 'Avg',
    'admin.max': 'Max',
    'admin.last7Days': 'Nakaraang 7 araw',
    'admin.last24Hours': 'Nakaraang 24 oras',
    'admin.last30Days': 'Nakaraang 30 araw',
    'admin.customPeriod': 'Custom period',
    'admin.noSalesData': 'Walang sales data sa petsang ito.',
    'admin.quickTips': 'Quick Tips',
    'admin.tipsDescription': 'Gamitin ang sidebar para sa sistema. I-access ang',
    'admin.userManagement': '👥 User Management',
    'admin.branchControl': '🏢 Branch Control',
    'admin.analytics': '📊 Analytics',
    'admin.trackPerformance': 'I-track ang performance',
    
    // Staff Dashboard
    'staff.dashboard': 'Staff Dashboard',
    'staff.items': 'Mga Item',
    'staff.suppliers': 'Mga Supplier',
    'staff.stocks': 'Mga Stock',
    'staff.addItem': 'Magdagdag ng Item',
    'staff.addSupplier': 'Magdagdag ng Supplier',
    'staff.addStocks': 'Magdagdag ng Stock',
    'staff.voidRequests': 'Void Requests',
    'staff.purchases': 'Mga Binili',
    'staff.changePassword': 'Palitan ang Password',
    
    // Cashier Dashboard
    'cashier.dashboard': 'Cashier Dashboard',
    'cashier.buyItem': 'Bumili ng Item',
    'cashier.sales': 'Benta',
    'cashier.holdItems': 'I-hold ang Items',
    'cashier.purchases': 'Mga Binili',
    'cashier.mainPanel': 'Main Panel',
    
    // Sidebar
    'sidebar.home': 'Home',
    'sidebar.dashboard': 'Dashboard',
    'sidebar.inventory': 'Imbentaryo',
    'sidebar.sales': 'Benta',
    'sidebar.reports': 'Mga Ulat',
    'sidebar.settings': 'Settings',
    
    // Purchases Page
    'purchases.title': 'Mga Binili',
    'purchases.subtitle': 'Kasaysayan ng transaksyon',
    'purchases.searchPlaceholder': 'Maghanap ng binili...',
    'purchases.found': 'nahanap',
    'purchases.voidRequests': 'Void Requests',
    'purchases.allPayments': 'Lahat ng Payment',
    'purchases.cash': 'Cash',
    'purchases.gcash': 'GCash',
    'purchases.allStatus': 'Lahat ng Status',
    'purchases.completed': 'Tapos na',
    'purchases.voided': 'Na-void',
    'purchases.purchaseHistory': 'Kasaysayan ng Binili',
    'purchases.allTransactionRecords': 'Lahat ng rekord ng transaksyon',
    'purchases.loading': 'Naglo-load ng mga binili...',
    'purchases.noPurchases': 'Walang nahanap na binili',
    'purchases.tryAdjusting': 'Subukan baguhin ang search',
    'purchases.saleId': 'Sale ID',
    'purchases.receiptNo': 'Receipt No.',
    'purchases.itemName': 'Pangalan ng Item',
    'purchases.dateTime': 'Petsa at Oras',
    'purchases.subtotal': 'Subtotal',
    'purchases.tax': 'Tax',
    'purchases.discount': 'Diskwento',
    'purchases.total': 'Total',
    'purchases.payment': 'Payment',
    'purchases.status': 'Status',
    'purchases.actions': 'Aksyon',
    'purchases.void': 'I-void',
    'purchases.alreadyVoided': 'Na-void na',
    'purchases.voidThisPurchase': 'I-void ang binili',
    'purchases.confirmVoid': 'Sigurado ka ba na gusto mong i-void ang biniling ito? Ibabalik ang stock.',
    'purchases.authError': 'Authorization error. Mag-login ulit.',
    'purchases.voidFailed': 'Hindi nag-succeed ang pag-void.',
    'purchases.tryAgain': 'Subukan ulit.',
    
    // Void Requests Page
    'voidRequests.title': 'Void Requests',
    'voidRequests.subtitle': 'I-review at aprubahan/tanggihan ang void requests mula sa mga cashier',
    'voidRequests.searchPlaceholder': 'Maghanap gamit ang receipt number, item name...',
    'voidRequests.loading': 'Naglo-load ng void requests...',
    'voidRequests.noRequests': 'Walang pending void requests',
    'voidRequests.allClear': 'All clear! Walang void requests sa ngayon.',
    'voidRequests.receiptNo': 'Receipt No.',
    'voidRequests.itemName': 'Pangalan ng Item',
    'voidRequests.dateTime': 'Petsa at Oras',
    'voidRequests.total': 'Total',
    'voidRequests.payment': 'Payment',
    'voidRequests.approve': 'Aprubahan',
    'voidRequests.reject': 'Tanggihan',
    'voidRequests.confirmApprove': 'Sigurado ka ba na gusto mong aprubahan ang void request? Ibabalik ang stock at ivo-void ang transaction.',
    'voidRequests.confirmReject': 'Sigurado ka ba na gusto mong tanggihan ang void request?',
    'voidRequests.approveSuccess': 'Nag-succeed ang pag-apruba ng void request',
    'voidRequests.rejectSuccess': 'Na-reject ang void request',
    'voidRequests.approveFailed': 'Hindi nag-succeed ang pag-apruba',
    'voidRequests.rejectFailed': 'Hindi nag-succeed ang pag-reject',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('appLanguage');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('appLanguage', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
